name: CI/CD com Docker e Terraform

on:
  push:
    branches:
      - featureActions
  pull_request:
    branches:
      - featureActions
  workflow_dispatch:

jobs:
  ci-cd-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagem Docker e fazer push
        id: build-image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${{ github.sha }}
          DOCKER_IMAGE_URL="${{ vars.DOCKER_USERNAME }}/gerenciador-despesas"
          
          docker build -t $DOCKER_IMAGE_URL:$IMAGE_TAG -t $DOCKER_IMAGE_URL:latest .
          docker push $DOCKER_IMAGE_URL:$IMAGE_TAG
          docker push $DOCKER_IMAGE_URL:latest

          echo "image_tag=$DOCKER_IMAGE_URL:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Inicializar Terraform
        run: |
          cd Infra
          terraform init -backend-config="bucket=devopsarrocha-terraform-bucket2025" -backend-config="key=github/terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}"
      
      - name: Validar e planejar Terraform
        run: |
          cd Infra
          terraform validate
          terraform plan

      - name: Aplicar Terraform
        run: |
          cd Infra
          terraform apply -auto-approve -var="app_image=${{ steps.build-image.outputs.image_tag }}"

  destroy-manual:
    runs-on: ubuntu-latest
    needs: ci-cd-apply
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Inicializar Terraform
        run: |
          cd Infra
          terraform init -backend-config="bucket=devopsarrocha-terraform-bucket2025" -backend-config="key=github/terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Destruir a infraestrutura
        run: |
          cd Infra
          terraform destroy -auto-approve

