name: "Example Workflow 1.2"

on:
  workflow_dispatch:
    

jobs:
  deploy:
    name: "Deploy ${{ matrix.environment }}"
    runs_on: ubuntu-24.04
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        environment: ["dev", "qa", "prod"]
    steps:
      - name: "Deploy ${{ matrix.environment }} step"
        run: echo "deploying ${ENVIRONMENT}"
        env:
          ENVIRONMENT: ${{ matrix.environment }}