name: SCHEDULE TURN-ON

on:
  workflow_dispatch:
    inputs:
      actions:
        type: multiselect
        description: "Selecione as ações a serem executadas"
        options:
          - deploy
          - build
          - test
      clients:
        type: multiselect
        description: "Selecione os clientes para Deploy/Build"
        options:
          - bridgestone
          - carrera
          - daf
          - dynamo
          - jdrede
          - man
          - michelin
          - multimarcaspneus
          - newhollandagriculture
          - mercedes

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar clientes selecionados
        run: |
          echo "Clientes selecionados: ${{ toJson(inputs.clients) }}"